(async()=>{'use strict';
const P=window.StatsPro2,E=window.Pro2Export,$=q=>document.querySelector(q);const params=new URLSearchParams(location.search),id=params.get('id');const store=new P.Pro2Storage(new P.IndexedDBStorageAdapter());
const TYPES=['SERVEI','RECEPCIO','DEFENSA','COLLOCACIO','ATAC'];const LABEL={SERVEI:'Servei',RECEPCIO:'Recepció',DEFENSA:'Defensa',COLLOCACIO:'Col·locació',ATAC:'Atac',BLOQUEIG:'Bloqueig',SALVADA:'Salvada'};const FOUNDATION_COLOR={SERVEI:'#d6b656',RECEPCIO:'#6fa8dc',DEFENSA:'#76a5af',COLLOCACIO:'#8e7cc3',ATAC:'#e69138',BLOQUEIG:'#93c47d'};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const fmt=v=>v==null?'—':(v*100).toFixed(1)+'%';const fmtN=v=>v==null?'—':(Number(v)%1?Number(v).toFixed(2):String(v));
function score(report){return String(report.metadata?.legacyResult||P.scoreText(report)).replace('-', '–')}function setScore(s){const sc=s.score||s.scores||s||{};const a=sc.team??sc.castellar,b=sc.rival;if(a==null||b==null)return '—';return `${a}–${b}`}
function setNumbers(report){const a=Object.keys(report.stats?.bySet||{}).map(Number).filter(Number.isInteger);const b=(report.result?.sets||[]).map(s=>Number(s.set)).filter(Number.isInteger);return [...new Set([...a,...b])].sort((x,y)=>x-y)}
function setEquivalent(p,sets){return sets.reduce((a,n)=>a+(p.participation?.sets?.[n]?.participation||0),0)}
function counts(p,t){return p.anna?.[t]?.counts||{0:0,1:0,2:0,3:0}}
function ratingHeaders(max=3,start=0){return Array.from({length:max-start+1},(_,i)=>`<th class="v${i+start}">${i+start}</th>`).join('')}
function blockHeaders(){return [0,1,2].map(v=>`<th class="block-v${v}">${v}</th>`).join('')}
function efficiencyScale(values){const xs=(values||[]).filter(v=>v!=null&&Number.isFinite(Number(v))).map(Number).sort((a,b)=>a-b);if(!xs.length)return null;const min=xs[0],max=xs[xs.length-1],mid=xs[Math.floor((xs.length-1)/2)];return {min,max,mid};}
function mixColor(a,b,t){t=Math.max(0,Math.min(1,Number(t)||0));const c=a.map((v,i)=>Math.round(v+(b[i]-v)*t));return `rgb(${c[0]}, ${c[1]}, ${c[2]})`;}
function efficiencyColor(v,scale){if(v==null||!scale)return '';const n=Number(v);if(!Number.isFinite(n))return '';const RED=[244,204,204],YELLOW=[255,242,204],GREEN=[217,234,211];if(scale.max===scale.min)return `rgb(${YELLOW[0]}, ${YELLOW[1]}, ${YELLOW[2]})`;const mid=(scale.mid>scale.min&&scale.mid<scale.max)?scale.mid:(scale.min+scale.max)/2;if(n<=mid){const d=mid-scale.min||1;return mixColor(RED,YELLOW,(n-scale.min)/d);}const d=scale.max-mid||1;return mixColor(YELLOW,GREEN,(n-mid)/d);}
function paintEfficiencyCell(el,v,scale){const c=efficiencyColor(v,scale);if(c){el.style.backgroundColor=c;el.style.color='#111';el.dataset.efficiency=String(v);}}
function paintEfficiencyRow(tr,v,scale){const c=efficiencyColor(v,scale);if(c){for(const td of tr.cells){td.style.backgroundColor=c;td.style.color='#111';}tr.dataset.efficiency=String(v);}}
function editCell(playerId,type,value,count,cls=`v${value}`){return `<td class="${cls} stat-edit-cell" data-player="${esc(playerId)}" data-type="${esc(type)}" data-value="${value}" data-count="${Number(count)||0}"><button type="button" class="count-step minus" aria-label="Resta una valoració ${value}">−</button><span class="stat-count">${Number(count)||0}</span><button type="button" class="count-step plus" aria-label="Suma una valoració ${value}">+</button></td>`}

function renderMain(report){
  const sets=setNumbers(report),thead=$('#matchTable thead'),tb=$('#matchTable tbody');
  thead.innerHTML=`<tr><th rowspan="2">DORSAL</th><th rowspan="2">JUGADORA</th><th class="group" colspan="${sets.length+1}">SETS</th>${TYPES.map(t=>`<th class="group" colspan="4">${LABEL[t].toUpperCase()}</th>`).join('')}<th class="group" colspan="3">BLOQUEIG</th><th class="group" colspan="3">SALVADES</th></tr><tr>${sets.map(n=>`<th>S${n}</th>`).join('')}<th>TOTAL</th>${TYPES.map(()=>ratingHeaders()).join('')}${blockHeaders()}${ratingHeaders(3,1)}</tr>`;
  tb.innerHTML='';
  for(const p of report.stats?.players||[]){
    const tr=document.createElement('tr');
    tr.innerHTML=`<td>${esc(p.number??'')}</td><td class="player">${esc(p.name||'')}</td>${sets.map(n=>`<td>${p.participation?.sets?.[n]?.participation==null?'':fmt(p.participation.sets[n].participation)}</td>`).join('')}<td><b>${fmtN(setEquivalent(p,sets))}</b></td>${TYPES.map(t=>[0,1,2,3].map(v=>editCell(p.playerId,t,v,counts(p,t)[v]||0)).join('')).join('')}${[0,1,2].map(v=>editCell(p.playerId,'BLOQUEIG',v,p.blocks?.counts?.[v]||0,`block-v${v}`)).join('')}${[1,2,3].map(v=>editCell(p.playerId,'SALVADA',v,p.saves?.counts?.[v]||0)).join('')}`;
    tb.appendChild(tr);
  }
}
function renderPercentages(report){
  const sets=setNumbers(report),thead=$('#percentageTable thead'),tb=$('#percentageTable tbody');
  thead.innerHTML=`<tr><th rowspan="2">DORSAL</th><th rowspan="2">JUGADORA</th><th rowspan="2">SETS</th>${TYPES.map(t=>`<th class="group" colspan="4">${LABEL[t].toUpperCase()}</th>`).join('')}<th class="group" colspan="3">BLOQUEIG</th><th class="group" colspan="3">SALVADES</th></tr><tr>${TYPES.map(()=>ratingHeaders()).join('')}${blockHeaders()}${ratingHeaders(3,1)}</tr>`;
  tb.innerHTML='';const team={};for(const t of TYPES)team[t]=report.stats?.teamAnna?.[t]||{};
  for(const p of report.stats?.players||[]){const tr=document.createElement('tr');tr.innerHTML=`<td>${esc(p.number??'')}</td><td class="player">${esc(p.name||'')}</td><td>${fmtN(setEquivalent(p,sets))}</td>${TYPES.map(t=>[0,1,2,3].map(v=>`<td class="v${v}">${fmt(p.anna?.[t]?.percentages?.[v])}</td>`).join('')).join('')}${[0,1,2].map(v=>`<td class="block-v${v}">${p.blocks?.total?fmt((p.blocks.counts?.[v]||0)/p.blocks.total):'—'}</td>`).join('')}${[1,2,3].map(v=>`<td class="v${v}">${p.saves?.counts?.[v]||0}</td>`).join('')}`;tb.appendChild(tr);}
  const tr=document.createElement('tr');tr.innerHTML=`<td></td><td class="player"><b>TOTAL EQUIP</b></td><td></td>${TYPES.map(t=>[0,1,2,3].map(v=>`<td class="v${v}"><b>${fmt(team[t]?.percentages?.[v])}</b></td>`).join('')).join('')}${[0,1,2].map(v=>`<td class="block-v${v}"><b>${report.stats?.teamBlocks?.total?fmt((report.stats.teamBlocks.counts?.[v]||0)/report.stats.teamBlocks.total):'—'}</b></td>`).join('')}${[1,2,3].map(v=>`<td class="v${v}"><b>${report.stats?.teamSaves?.counts?.[v]||0}</b></td>`).join('')}`;tb.appendChild(tr);
}
function assessment(p){if(!p.actions)return 'Sense accions registrades en aquest partit; no es pot fer una valoració fiable.';const base=p.efficiency>=.70?'Rendiment global molt positiu':p.efficiency>=.60?'Rendiment sòlid':p.efficiency>=.50?'Rendiment acceptable':'Rendiment irregular';const s=p.strength?`${p.strength.label.toLowerCase()} com a principal fortalesa`:'sense una fortalesa prou definida';const q=p.priority?`Prioritat en ${p.priority.label.toLowerCase()} per guanyar regularitat.`:'';return `${base}, amb ${s}. ${q}${p.sampleSmall?' Mostra reduïda: dada orientativa.':''}`}
function renderAnna(report,a){
  $('#kpis').innerHTML=[['ACCIONS',a.actions],['EFICIÈNCIA EQUIP',fmt(a.efficiency)],['MILLOR SET',a.bestSet?`Set ${a.bestSet.set} · ${fmt(a.bestSet.efficiency)}`:'—'],['MILLOR EFICIÈNCIA',a.bestEfficiency?`${esc(a.bestEfficiency.name)} · ${fmt(a.bestEfficiency.efficiency)}`:'—'],['MÉS IMPACTE',a.mostImpact?`${esc(a.mostImpact.name)} · ${fmt(a.mostImpact.impact)}`:'—']].map(x=>`<div class="kpi"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join('');
  const tb=$('#technicalPlayers tbody');tb.innerHTML='';const individual=[...(a.players||[])].sort((x,y)=>(y.efficiency??-1)-(x.efficiency??-1)||(y.impact??-1)-(x.impact??-1)||(y.actions??0)-(x.actions??0)),individualScale=efficiencyScale(individual.filter(x=>x.actions).map(x=>x.efficiency));for(const p of individual){const tr=document.createElement('tr');tr.innerHTML=`<td class="player">${esc(p.name)}</td><td>${fmtN(p.actions)}</td><td>${fmt(p.efficiency)}</td><td>${fmt(p.impact)}</td><td>${esc(p.strength?.label||'—')}</td><td>${fmt(p.strength?.efficiency)}</td><td>${esc(p.priority?.label||'—')}</td><td>${fmt(p.priority?.efficiency)}</td><td class="player">${esc(assessment(p))}</td>`;if(p.actions)paintEfficiencyRow(tr,p.efficiency,individualScale);tb.appendChild(tr);}
  const rank=$('#ranking tbody');rank.innerHTML='';const ordered=[...(a.ranking||[])].sort((x,y)=>(y.efficiency??-1)-(x.efficiency??-1)||(y.impact??-1)-(x.impact??-1)||(y.actions??0)-(x.actions??0)),rankScale=efficiencyScale(ordered.filter(x=>x.actions).map(x=>x.efficiency));
  for(const p of ordered){const tr=document.createElement('tr');tr.innerHTML=`<td class="player"><span class="eff-player">${esc(p.name)}</span></td><td>${fmtN(p.actions)}</td><td><b>${fmt(p.efficiency)}</b></td><td>${fmt(p.impact)}</td>`;if(p.actions)paintEfficiencyRow(tr,p.efficiency,rankScale);rank.appendChild(tr);}
  const strong=a.strengths.map(x=>`${x.label} (${fmt(x.efficiency)})`).join('; ');const pri=a.priorities.map(x=>`${x.label} (${fmt(x.efficiency)})`).join('; ');$('#conclusions').innerHTML=`<p><b>FORTALESES ·</b> ${esc(strong||'Sense prou dades.')}</p><p><b>PRIORITAT 1 ·</b> ${esc(a.priorities[0]?.label||'—')}: reduir accions de valor 0 i augmentar continuïtat.</p><p><b>PRIORITAT 2 ·</b> ${esc(a.priorities[1]?.label||'—')}: millorar qualitat mitjana i regularitat.</p><p class="muted">Prioritats ordenades segons l'eficiència 0–5–8–10 del partit. ${esc(pri)}</p>`;
}
function renderDetail(report,a){
 let tb=$('#foundationSummary tbody');tb.innerHTML='';const foundationScale=efficiencyScale((a.teamFoundations||[]).filter(x=>x.actions).map(x=>x.efficiency));for(const f of a.teamFoundations){const b=report.stats.teamAnna[f.type];const tr=document.createElement('tr');tr.innerHTML=`<td class="player">${esc(f.label)}</td><td>${fmtN(f.actions)}</td><td class="eff-cell">${fmt(f.efficiency)}</td>${[0,1,2,3].map(v=>`<td class="v${v}">${fmt(b.percentages?.[v])}</td>`).join('')}`;if(f.actions)paintEfficiencyCell(tr.cells[2],f.efficiency,foundationScale);tb.appendChild(tr);}
 tb=$('#setSummary tbody');tb.innerHTML='';const setScale=efficiencyScale((a.sets||[]).filter(x=>x.actions).map(x=>x.efficiency));for(const st of a.sets){const b=report.stats.bySet[st.set].teamAnnaTotal;const tr=document.createElement('tr');tr.innerHTML=`<td>${st.set}</td><td>${fmtN(st.actions)}</td><td class="eff-cell">${fmt(st.efficiency)}</td>${[0,1,2,3].map(v=>`<td class="v${v}">${fmt(b.percentages?.[v])}</td>`).join('')}`;if(st.actions)paintEfficiencyCell(tr.cells[2],st.efficiency,setScale);tb.appendChild(tr);}
 const head=$('#playerFoundation thead');head.innerHTML=`<tr><th rowspan="2">Jugadora</th>${TYPES.map(t=>`<th class="group" colspan="4">${LABEL[t].toUpperCase()}</th>`).join('')}<th class="group" colspan="3">BLOQUEIG</th><th rowspan="2">Eficiència</th><th rowspan="2">Impacte</th></tr><tr>${TYPES.map(()=>ratingHeaders()).join('')}${blockHeaders()}</tr>`;
 tb=$('#playerFoundation tbody');tb.innerHTML='';const analyticsById=new Map((a.players||[]).map(x=>[String(x.playerId),x])),playerEffScale=efficiencyScale((a.players||[]).filter(x=>x.actions).map(x=>x.efficiency));for(const p of report.stats.players||[]){const ap=analyticsById.get(String(p.playerId));const tr=document.createElement('tr');tr.innerHTML=`<td class="player">${esc(p.name)}</td>${TYPES.map(t=>[0,1,2,3].map(v=>`<td class="v${v}">${counts(p,t)[v]||0}</td>`).join('')).join('')}${[0,1,2].map(v=>`<td class="block-v${v}">${p.blocks?.counts?.[v]||0}</td>`).join('')}<td class="eff-cell"><b>${fmt(ap?.efficiency)}</b></td><td><b>${fmt(ap?.impact)}</b></td>`;if(ap?.actions)paintEfficiencyCell(tr.cells[tr.cells.length-2],ap.efficiency,playerEffScale);tb.appendChild(tr);}
 tb=$('#specials tbody');tb.innerHTML='';for(const p of report.stats.players||[]){const tr=document.createElement('tr');tr.innerHTML=`<td class="player">${esc(p.name)}</td>${[1,2,3].map(v=>`<td class="v${v}">${p.saves?.counts?.[v]||0}</td>`).join('')}<td><b>${p.saves?.total||0}</b></td>${[0,1,2].map(v=>`<td class="block-v${v}">${p.blocks?.counts?.[v]||0}</td>`).join('')}<td><b>${p.blocks?.total||0}</b></td>`;tb.appendChild(tr);}
}
function colorForSeries(s,si){const key=s.type||Object.keys(LABEL).find(k=>LABEL[k]===s.name);return FOUNDATION_COLOR[key]||['#5b7fa3','#c27c46','#7b8f58','#9a6fb0','#5f8f8a','#8d6e63'][si%6];}
function svgLine(series,width=720,height=260){const all=series.flatMap(s=>s.values.filter(v=>v!=null));if(!all.length)return '<div class="muted">Sense dades.</div>';const min=Math.max(0,Math.min(...all)-.05),max=Math.min(1,Math.max(...all)+.05),pad={l:45,r:15,t:24,b:42},w=width-pad.l-pad.r,h=height-pad.t-pad.b,n=Math.max(...series.map(s=>s.values.length),1),x=i=>pad.l+(n<=1?w/2:i*w/(n-1)),y=v=>pad.t+h-(v-min)/(max-min||1)*h;let out=`<svg viewBox="0 0 ${width} ${height}" role="img">`;for(let k=0;k<5;k++){const yy=pad.t+k*h/4,val=max-k*(max-min)/4;out+=`<line x1="${pad.l}" y1="${yy}" x2="${width-pad.r}" y2="${yy}" stroke="#ddd"/><text x="3" y="${yy+4}" font-size="10">${Math.round(val*100)}%</text>`}series.forEach((ser,si)=>{const color=colorForSeries(ser,si),pts=ser.values.map((v,i)=>v==null?null:`${x(i)},${y(v)}`).filter(Boolean).join(' ');if(pts)out+=`<polyline points="${pts}" fill="none" stroke="${color}" stroke-width="3"/>`;ser.values.forEach((v,i)=>{if(v!=null)out+=`<circle cx="${x(i)}" cy="${y(v)}" r="3.5" fill="${color}"/>`});out+=`<g><rect x="${pad.l+si*118-5}" y="2" width="10" height="10" rx="2" fill="${color}"/><text x="${pad.l+si*118+9}" y="11" font-size="10">${esc(ser.name)}</text></g>`});const labels=series[0]?.labels||[];labels.forEach((l,i)=>out+=`<text x="${x(i)}" y="${height-10}" text-anchor="middle" font-size="9">${esc(String(l).slice(0,14))}</text>`);return out+'</svg>';}

function svgLineWindow(series,width=720,height=260,start=0,count=5){
  const nAll=Math.max(...series.map(s=>s.values?.length||0),0);if(!nAll)return '<div class="muted">Sense dades.</div>';
  const end=Math.min(nAll,start+count),slice=series.map(s=>({...s,values:(s.values||[]).slice(start,end),labels:(s.labels||[]).slice(start,end)}));
  const all=slice.flatMap(s=>s.values.filter(v=>v!=null));if(!all.length)return '<div class="muted">Sense dades.</div>';
  const min=0,max=1,pad={l:45,r:15,t:24,b:42},w=width-pad.l-pad.r,h=height-pad.t-pad.b,n=Math.max(...slice.map(s=>s.values.length),1),x=i=>pad.l+(n<=1?w/2:i*w/(n-1)),y=v=>pad.t+h-(v-min)/(max-min)*h;
  let out=`<svg viewBox="0 0 ${width} ${height}" role="img" aria-label="Evolució històrica, eix de 0 a 100%">`;
  for(let k=0;k<5;k++){const yy=pad.t+k*h/4,val=1-k/4;out+=`<line x1="${pad.l}" y1="${yy}" x2="${width-pad.r}" y2="${yy}" stroke="#ddd"/><text x="3" y="${yy+4}" font-size="10">${Math.round(val*100)}%</text>`}
  slice.forEach((ser,si)=>{const color=colorForSeries(ser,si),pts=ser.values.map((v,i)=>v==null?null:`${x(i)},${y(v)}`).filter(Boolean).join(' ');if(pts)out+=`<polyline points="${pts}" fill="none" stroke="${color}" stroke-width="3"/>`;ser.values.forEach((v,i)=>{if(v!=null)out+=`<circle cx="${x(i)}" cy="${y(v)}" r="3.5" fill="${color}"/>`});out+=`<g><rect x="${pad.l+si*118-5}" y="2" width="10" height="10" rx="2" fill="${color}"/><text x="${pad.l+si*118+9}" y="11" font-size="10">${esc(ser.name)}</text></g>`});
  const labels=slice[0]?.labels||[];labels.forEach((l,i)=>out+=`<text x="${x(i)}" y="${height-10}" text-anchor="middle" font-size="9">${esc(String(l).slice(0,14))}</text>`);return out+'</svg>';
}
function mountHistoryChart(target,series,width=720,height=260){
  if(!target)return;target.innerHTML='';const n=Math.max(...series.map(s=>s.values?.length||0),0),visible=Math.min(5,Math.max(n,1)),maxStart=Math.max(0,n-visible),initial=maxStart;
  const wrap=document.createElement('div');wrap.className='history-chart-window';const frame=document.createElement('div');frame.className='history-chart-frame';const slider=document.createElement('div');slider.className='history-chart-slider';const note=document.createElement('div');note.className='history-chart-note';
  const range=document.createElement('input');range.type='range';range.min='0';range.max=String(maxStart);range.step='1';range.value=String(initial);range.setAttribute('aria-label','Moure la finestra de partits, dels més antics als més recents');
  slider.innerHTML='<span>Més antics</span>';slider.appendChild(range);slider.insertAdjacentHTML('beforeend','<span>Més recents</span>');if(maxStart===0)slider.hidden=true;
  const render=start=>{const a=Math.max(0,Math.min(maxStart,Number(start)||0));frame.innerHTML=svgLineWindow(series,width,height,a,visible);const first=a+1,last=Math.min(n,a+visible);note.textContent=n>visible?`Partits ${first}–${last} de ${n} · per defecte es mostren els 5 més recents`:`${n} partit(s) a l’anàlisi`;};
  range.addEventListener('input',()=>render(range.value));wrap.append(frame,slider,note);target.appendChild(wrap);render(initial);
}
function svgBars(items,width=720,height=250){const valid=items.filter(it=>it.value!=null);if(!items.length||!valid.length)return '<div class="muted">Sense dades.</div>';const pad={l:45,r:15,t:15,b:55},w=width-pad.l-pad.r,h=height-pad.t-pad.b,bw=w/items.length*.6,gap=w/items.length;let out=`<svg viewBox="0 0 ${width} ${height}">`;for(let k=0;k<5;k++){const y=pad.t+k*h/4;out+=`<line x1="${pad.l}" y1="${y}" x2="${width-pad.r}" y2="${y}" stroke="#ddd"/><text x="3" y="${y+4}" font-size="10">${100-k*25}%</text>`}items.forEach((it,i)=>{const x=pad.l+i*gap+(gap-bw)/2;if(it.value==null){out+=`<text x="${x+bw/2}" y="${pad.t+h/2}" text-anchor="middle" font-size="10" fill="#777">Sense dades</text><text x="${x+bw/2}" y="${height-20}" text-anchor="middle" font-size="9">${esc(it.label)}</text>`;return;}const v=it.value,bh=v*h,y=pad.t+h-bh,color=FOUNDATION_COLOR[it.type]||'#5b7fa3';out+=`<rect x="${x}" y="${y}" width="${bw}" height="${bh}" fill="${color}"/><text x="${x+bw/2}" y="${height-20}" text-anchor="middle" font-size="9">${esc(it.label)}</text><text x="${x+bw/2}" y="${Math.max(12,y-3)}" text-anchor="middle" font-size="9">${Math.round(v*100)}%</text>`});return out+'</svg>';}
function fmtPp(v){return v==null?'—':`${v>=0?'+':''}${(v*100).toFixed(1)} pp`;}
function matchLabel(m){return esc(m?.opponent||'Partit');}
function rowForMatch(player,matchId){return (player?.matches||[]).find(m=>String(m.matchId)===String(matchId))||null;}
function renderHistory(h){
  $('#historyKpis').innerHTML=[['PARTITS',h.matches],['ACCIONS',h.teamTotal.actions],['EFICIÈNCIA GLOBAL',fmt(h.teamTotal.efficiency)],['% DE 0',fmt(h.teamTotal.percentages?.[0])],['% DE 3',fmt(h.teamTotal.percentages?.[3])]].map(x=>`<div class="kpi"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join('');
  mountHistoryChart($('#chartTeam'),[{name:'Eficiència',values:h.perMatch.map(m=>m.efficiency),labels:h.perMatch.map(m=>m.opponent)}]);
  const foundationBars=svgBars(h.teamFoundations.map(f=>({label:f.label||LABEL[f.type]||f.type,type:f.type,value:f.actions?f.efficiency:null})));
  $('#chartFoundations').innerHTML=foundationBars;$('#chartFoundationsMirror').innerHTML=foundationBars;
  const totalActions=h.teamTotal.actions||0,histPlayers=h.players||[],matches=h.perMatch||[];
  const select=$('#historyPlayerSelect'),previous=select.value;select.innerHTML=histPlayers.map((p,i)=>`<option value="${esc(p.playerId)}"${String(p.playerId)===String(previous)||(!previous&&i===0)?' selected':''}>${esc(p.name)}</option>`).join('');
  function renderSelectedPlayer(playerId){
    const p=histPlayers.find(x=>String(x.playerId)===String(playerId))||histPlayers[0];if(!p)return;
    const playerLabel=`#${p.number??''} ${p.name||''}`.trim();
    const contextName=$('#individualContextName');if(contextName)contextName.textContent=playerLabel;
    document.querySelectorAll('.selected-player-name').forEach(el=>el.textContent=playerLabel);
    const tb=$('#historyIndividual tbody');tb.innerHTML='';const effScale=efficiencyScale((p.matches||[]).filter(m=>m.actions>0).map(m=>m.efficiency));
    for(const m of matches){const pm=rowForMatch(p,m.matchId),tr=document.createElement('tr');tr.innerHTML=`<td class="player">${matchLabel(m)}</td><td>${pm?fmtN(pm.actions):'—'}</td><td class="eff-cell">${pm&&pm.actions?fmt(pm.efficiency):'—'}</td><td>${pm&&pm.actions?fmt(pm.impact):'—'}</td><td>${pm&&pm.actions?fmt(pm.pct0):'—'}</td><td>${pm&&pm.actions?fmt(pm.pct3):'—'}</td>`;if(pm&&pm.actions)paintEfficiencyCell(tr.cells[2],pm.efficiency,effScale);tb.appendChild(tr);}
    const impact=totalActions?p.total.annaPoints/(totalActions*10):null,acc=document.createElement('tr');acc.className='summary-row';acc.innerHTML=`<td class="player"><b>Acumulat</b></td><td><b>${fmtN(p.total.actions)}</b></td><td class="eff-cell"><b>${fmt(p.total.efficiency)}</b></td><td><b>${fmt(impact)}</b></td><td><b>${fmt(p.pct0)}</b></td><td><b>${fmt(p.pct3)}</b></td>`;paintEfficiencyCell(acc.cells[2],p.total.efficiency,efficiencyScale(histPlayers.filter(x=>x.total?.actions).map(x=>x.total.efficiency)));tb.appendChild(acc);
    mountHistoryChart($('#chartIndividual'),[{name:'Eficiència',values:matches.map(m=>{const pm=rowForMatch(p,m.matchId);return pm&&pm.actions?pm.efficiency:null;}),labels:matches.map(m=>m.opponent)}],620,220);
    const head=$('#historyPlayerFoundationEvolution thead');head.innerHTML=`<tr><th>Fonament</th>${matches.map(m=>`<th>${matchLabel(m)}</th>`).join('')}<th>Evolució</th><th>% 0 inicial</th><th>% 0 final</th><th>Reducció errors</th><th>Tendència</th></tr>`;
    const body=$('#historyPlayerFoundationEvolution tbody');body.innerHTML='';const colScales=matches.map((m,idx)=>efficiencyScale((p.foundationEvolution||[]).map(f=>f.rows?.[idx]).filter(r=>r&&r.actions>0).map(r=>r.efficiency)));
    for(const f of p.foundationEvolution||[]){const tr=document.createElement('tr'),valid=(f.rows||[]).filter(r=>r.actions>0&&r.efficiency!=null),first=valid[0],last=valid[valid.length-1];tr.innerHTML=`<td class="player">${esc(f.label||LABEL[f.type]||f.type)}</td>${matches.map((m,idx)=>{const r=f.rows?.[idx];return `<td class="eff-cell">${r&&r.actions?fmt(r.efficiency):'—'}</td>`}).join('')}<td>${fmtPp(f.delta)}</td><td>${first?fmt(first.pct0):'—'}</td><td>${last?fmt(last.pct0):'—'}</td><td>${f.errorReduction==null?'—':fmtPp(f.errorReduction)}</td><td><b>${esc(f.trend)}</b></td>`;matches.forEach((m,idx)=>{const r=f.rows?.[idx];if(r&&r.actions)paintEfficiencyCell(tr.cells[1+idx],r.efficiency,colScales[idx]);});body.appendChild(tr);}
    mountHistoryChart($('#chartPlayerFoundationEvolution'),(p.foundationEvolution||[]).map(f=>({name:f.label||LABEL[f.type]||f.type,type:f.type,values:(f.rows||[]).map(r=>r.actions?r.efficiency:null),labels:(f.rows||[]).map(r=>r.opponent)})));
  }
  select.onchange=()=>renderSelectedPlayer(select.value);renderSelectedPlayer(select.value);
  const hpHead=$('#historyPlayers thead');hpHead.innerHTML=`<tr><th>Jugadora</th><th>Accions</th><th>Eficiència acum.</th>${matches.map(m=>`<th>${matchLabel(m)}</th>`).join('')}<th>Evolució</th><th>Impacte*</th><th>% de 0</th><th>% de 3</th><th>Tendència</th></tr>`;
  let tb=$('#historyPlayers tbody');tb.innerHTML='';const accScale=efficiencyScale(histPlayers.filter(p=>p.total?.actions).map(p=>p.total.efficiency)),matchScales=matches.map(m=>efficiencyScale(histPlayers.map(p=>rowForMatch(p,m.matchId)).filter(pm=>pm&&pm.actions).map(pm=>pm.efficiency)));
  for(const p of histPlayers){const impact=totalActions?p.total.annaPoints/(totalActions*10):null,tr=document.createElement('tr');tr.innerHTML=`<td class="player">${esc(p.name)}</td><td>${fmtN(p.total.actions)}</td><td class="eff-cell">${fmt(p.total.efficiency)}</td>${matches.map(m=>{const pm=rowForMatch(p,m.matchId);return `<td class="eff-cell">${pm&&pm.actions?fmt(pm.efficiency):'—'}</td>`}).join('')}<td>${fmtPp(p.delta)}</td><td>${fmt(impact)}</td><td>${fmt(p.pct0)}</td><td>${fmt(p.pct3)}</td><td><b>${esc(p.trend)}</b></td>`;if(p.total?.actions)paintEfficiencyCell(tr.cells[2],p.total.efficiency,accScale);matches.forEach((m,idx)=>{const pm=rowForMatch(p,m.matchId);if(pm&&pm.actions)paintEfficiencyCell(tr.cells[3+idx],pm.efficiency,matchScales[idx]);});tb.appendChild(tr);}
  tb=$('#historyFoundations tbody');tb.innerHTML='';const histFoundationScale=efficiencyScale((h.teamFoundations||[]).filter(f=>f.actions).map(f=>f.efficiency));for(const f of h.teamFoundations){const tr=document.createElement('tr');tr.innerHTML=`<td class="player">${esc(f.label||LABEL[f.type]||f.type||'—')}</td><td>${fmtN(f.actions)}</td><td class="eff-cell">${f.actions?fmt(f.efficiency):'Sense dades'}</td>${[0,1,2,3].map(v=>`<td class="v${v}">${f.actions?fmt(f.percentages?.[v]):'—'}</td>`).join('')}`;if(f.actions)paintEfficiencyCell(tr.cells[2],f.efficiency,histFoundationScale);tb.appendChild(tr);}
  const hfHead=$('#historyFoundationEvolution thead');hfHead.innerHTML=`<tr><th>Fonament</th>${matches.map(m=>`<th>${matchLabel(m)}</th>`).join('')}<th>Evolució</th><th>% 0 inicial</th><th>% 0 final</th><th>Reducció errors</th><th>Tendència global</th></tr>`;
  const hfBody=$('#historyFoundationEvolution tbody');hfBody.innerHTML='';const hfScales=matches.map((m,idx)=>efficiencyScale((h.teamFoundationEvolution||[]).map(f=>f.rows?.[idx]).filter(r=>r&&r.actions>0).map(r=>r.efficiency)));
  for(const f of h.teamFoundationEvolution||[]){const tr=document.createElement('tr'),valid=(f.rows||[]).filter(r=>r.actions>0&&r.efficiency!=null),first=valid[0],last=valid[valid.length-1];tr.innerHTML=`<td class="player">${esc(f.label||LABEL[f.type]||f.type)}</td>${matches.map((m,idx)=>{const r=f.rows?.[idx];return `<td class="eff-cell">${r&&r.actions?fmt(r.efficiency):'—'}</td>`}).join('')}<td>${fmtPp(f.delta)}</td><td>${first?fmt(first.pct0):'—'}</td><td>${last?fmt(last.pct0):'—'}</td><td>${f.errorReduction==null?'—':fmtPp(f.errorReduction)}</td><td><b>${esc(f.trend)}</b></td>`;matches.forEach((m,idx)=>{const r=f.rows?.[idx];if(r&&r.actions)paintEfficiencyCell(tr.cells[1+idx],r.efficiency,hfScales[idx]);});hfBody.appendChild(tr);}
  mountHistoryChart($('#chartFoundationEvolution'),h.teamFoundationEvolution.map(f=>({name:f.label||LABEL[f.type]||f.type,type:f.type,values:f.rows.map(r=>r.actions?r.efficiency:null),labels:f.rows.map(r=>r.opponent)})));
  const root=$('#playerEvolution');root.innerHTML='';for(const p of histPlayers){const div=document.createElement('div');div.className='player-evolution-block';div.innerHTML=`<h3>#${esc(p.number)} ${esc(p.name)} · ${esc(p.trend)}</h3><div class="player-evolution-grid"><div class="player-chart player-chart-eff"></div><div class="player-chart player-chart-found"></div></div>`;root.appendChild(div);mountHistoryChart(div.querySelector('.player-chart-eff'),[{name:'Eficiència',values:(p.matches||[]).map(m=>m.actions?m.efficiency:null),labels:(p.matches||[]).map(m=>m.opponent)}],620,220);mountHistoryChart(div.querySelector('.player-chart-found'),(p.foundationEvolution||[]).map(f=>({name:f.label||LABEL[f.type]||f.type,type:f.type,values:(f.rows||[]).map(r=>r.actions?r.efficiency:null),labels:(f.rows||[]).map(r=>r.opponent)})),620,220);}
}

function editableActions(report){return (report.actions||[]).filter(a=>['SERVEI','RECEPCIO','DEFENSA','COLLOCACIO','ATAC','BLOQUEIG','SALVADA'].includes(a.type)&&Number.isInteger(a.value));}
function setupEditor(report,rec){
  const table=$('#matchTable'),btn=$('#editBtn'),status=$('#editStatus'),statusText=$('#editStatusText'),cancel=$('#cancelPendingEdit');
  const all=editableActions(report).filter(a=>a.actionId);let mode=false,pending=null,busy=false;
  function baseMessage(){const n=rec.postMatchEdits?.edits?.length||0;return `Mode edició: prem − al valor actual i després + al valor correcte.${n?` · ${n} edició(ns) postpartit registrades.`:''}`;}
  function cells(){return [...table.querySelectorAll('.stat-edit-cell')];}
  function resetPreview(){for(const c of cells()){c.classList.remove('pending-source','pending-target');const x=c.querySelector('.stat-count');if(x)x.textContent=c.dataset.count;}cancel.hidden=true;statusText.textContent=baseMessage();}
  function setMode(on){mode=!!on;document.body.classList.toggle('edit-mode',mode);status.hidden=!mode;btn.textContent=mode?'Acaba edició':'Editar estadístiques';if(!mode){pending=null;resetPreview();}else statusText.textContent=baseMessage();}
  function candidates(player,type,value){return all.filter(a=>String(a.playerId)===String(player)&&a.type===type&&Number(a.value)===Number(value)).sort((a,b)=>(Number(b.sequence)||0)-(Number(a.sequence)||0));}
  function chooseSource(cell){const player=cell.dataset.player,type=cell.dataset.type,value=Number(cell.dataset.value),count=Number(cell.dataset.count)||0;if(count<1){statusText.textContent='No pots restar: aquesta casella és 0.';return;}const source=candidates(player,type,value)[0];if(!source){statusText.textContent='No s’ha trobat una acció original per reclassificar.';return;}pending={actionId:source.actionId,player,type,sourceValue:value,playerName:source.playerName||'',label:LABEL[type]||type};resetPreview();pending={actionId:source.actionId,player,type,sourceValue:value,playerName:source.playerName||'',label:LABEL[type]||type};cell.classList.add('pending-source');cell.querySelector('.stat-count').textContent=String(count-1);for(const c of cells())if(c.dataset.player===player&&c.dataset.type===type&&Number(c.dataset.value)!==value)c.classList.add('pending-target');cancel.hidden=false;statusText.textContent=`${source.playerName||'Jugadora'} · ${LABEL[type]||type}: has restat un ${value}. Ara prem + al valor correcte.`;}
  async function chooseTarget(cell){if(!pending){statusText.textContent='Primer prem − al valor que vols corregir.';return;}if(cell.dataset.player!==pending.player||cell.dataset.type!==pending.type){statusText.textContent='El + ha de ser de la mateixa jugadora i del mateix fonament.';return;}const target=Number(cell.dataset.value);if(target===pending.sourceValue){pending=null;resetPreview();return;}if(busy)return;busy=true;table.classList.add('editing-busy');try{await store.editHistoryActionValue(id,pending.actionId,target);location.reload();}catch(e){busy=false;table.classList.remove('editing-busy');statusText.textContent=e.message||String(e);}}
  table.addEventListener('click',e=>{if(!mode||busy)return;const step=e.target.closest('.count-step');if(!step)return;const cell=step.closest('.stat-edit-cell');if(!cell)return;if(step.classList.contains('minus'))chooseSource(cell);else chooseTarget(cell);});
  btn.onclick=()=>setMode(!mode);cancel.onclick=()=>{pending=null;resetPreview();};
  setMode(false);
}
const ANALYSIS_SELECTION_PREFIX='analysisSelection:';
let analysisReports=[],historyAnalytics=null;
function reportDateKey(r){return `${r?.metadata?.date||''}|${r?.matchId||''}`;}
async function initialAnalysisIds(teamReports,teamId,currentId){
  const valid=new Set(teamReports.map(r=>String(r.matchId))),mode=params.get('analysis');
  if(mode==='all')return new Set(valid);
  const saved=await store.adapter.get('settings',ANALYSIS_SELECTION_PREFIX+(teamId||'default'));
  const ids=Array.isArray(saved?.matchIds)?saved.matchIds.map(String).filter(x=>valid.has(x)):[];
  const out=new Set(ids.length?ids:[...valid]);out.add(String(currentId));return out;
}
async function persistAnalysisIds(teamId,ids){await store.adapter.put('settings',ANALYSIS_SELECTION_PREFIX+(teamId||'default'),{schemaVersion:1,teamId:teamId||null,matchIds:[...ids],updatedAt:new Date().toISOString()});}
function setupAnalysisFilter(report,teamReports,selectedIds,onApply){
  const list=$('#analysisMatchList'),actions=$('#analysisFilterActions'),toggle=$('#toggleAnalysisMatches'),apply=$('#applyAnalysisSelection'),allBtn=$('#analysisAll'),last5=$('#analysisLatest5'),status=$('#analysisFilterStatus');
  const sorted=[...teamReports].sort((a,b)=>reportDateKey(a).localeCompare(reportDateKey(b))),current=String(report.matchId),boxes=new Map();
  function labelOf(r){const d=r.metadata?.date?`${r.metadata.date} · `:'';return `${d}${r.metadata?.opponent||'Rival'}`;}
  function updateStatus(){const n=[...boxes.values()].filter(x=>x.checked).length;status.textContent=`${n} partit(s) inclosos. Les taules i gràfiques històriques es recalculen només amb aquesta selecció.`;apply.disabled=n<1;}
  function render(){list.innerHTML='';boxes.clear();for(const r of sorted){const sid=String(r.matchId),lab=document.createElement('label'),cb=document.createElement('input');cb.type='checkbox';cb.checked=selectedIds.has(sid)||sid===current;if(sid===current){cb.checked=true;cb.disabled=true;lab.title='El partit que tens obert sempre queda inclòs.';}cb.addEventListener('change',updateStatus);boxes.set(sid,cb);lab.append(cb,document.createTextNode(labelOf(r)+(sid===current?' · Actual':'')));list.appendChild(lab);}updateStatus();}
  toggle.onclick=()=>{const opening=list.hidden;list.hidden=!opening;actions.hidden=!opening;toggle.textContent=opening?'Amaga selecció':'Canvia selecció';};
  allBtn.onclick=()=>{for(const cb of boxes.values())if(!cb.disabled)cb.checked=true;updateStatus();};
  last5.onclick=()=>{for(const cb of boxes.values())if(!cb.disabled)cb.checked=false;const ids=sorted.map(r=>String(r.matchId)),latest=ids.slice(-5);if(!latest.includes(current)){const others=ids.filter(x=>x!==current).slice(-4);for(const sid of [...others,current])boxes.get(sid)&&(boxes.get(sid).checked=true);}else for(const sid of latest)boxes.get(sid)&&(boxes.get(sid).checked=true);updateStatus();};
  apply.onclick=async()=>{const ids=new Set([...boxes].filter(([,cb])=>cb.checked).map(([sid])=>sid));ids.add(current);await persistAnalysisIds(report.metadata?.teamId,ids);selectedIds.clear();for(const x of ids)selectedIds.add(x);await onApply(ids);updateStatus();};
  render();
}
try{
  if(!id)throw new Error('Falta l\'identificador del partit.');
  const rec=await store.getHistory(id);if(!rec||!rec.report)throw new Error('No s\'ha trobat aquest partit a l\'Historial.');
  const prepared=P.prepareVerifiedExport(rec),report=prepared.report,exportAudit=prepared.audit;const all=await store.listHistoryVerified();
  const reportPairs=all.map(r=>({record:r,report:P.reportFromCompletedRecord(r)})).filter(x=>x.report);const teamPairs=reportPairs.filter(x=>!report.metadata?.teamId||x.report.metadata?.teamId===report.metadata.teamId),sameTeam=teamPairs.map(x=>x.report);
  const selectedIds=await initialAnalysisIds(sameTeam,report.metadata?.teamId,id);selectedIds.add(String(id));
  const a=P.buildMatchAnalytics(report);
  async function applyHistorySelection(ids){analysisReports=sameTeam.filter(r=>ids.has(String(r.matchId)));if(!analysisReports.some(r=>String(r.matchId)===String(id)))analysisReports.push(report);historyAnalytics=P.buildHistoryAnalytics(analysisReports,{teamId:report.metadata?.teamId||null});renderHistory(historyAnalytics);}
  await applyHistorySelection(selectedIds);
  $('#subtitle').textContent=report.metadata?.date||'';$('#team').textContent=report.metadata?.teamName||'';$('#rival').textContent=report.metadata?.opponent||'Rival';$('#date').textContent=report.metadata?.date||'';$('#venue').textContent=report.metadata?.venue==='home'?'Casa':report.metadata?.venue==='away'?'Fora':'';$('#score').textContent=score(report);$('#setScores').textContent=(report.result?.sets||[]).map(s=>`S${s.set} ${setScore(s)}`).join('   ');
  renderMain(report);renderPercentages(report);renderAnna(report,a);renderDetail(report,a);setupEditor(report,rec);setupAnalysisFilter(report,sameTeam,selectedIds,applyHistorySelection);$('#report').hidden=false;
  $('#toggleAdvanced').onclick=()=>{const x=$('#advanced');x.hidden=!x.hidden;$('#toggleAdvanced').textContent=x.hidden?'Veure anàlisi completa':'Amaga anàlisi completa'};
  if(location.hash==='#advanced'||params.get('analysis')){$('#advanced').hidden=false;$('#toggleAdvanced').textContent='Amaga anàlisi completa';}
  let _advancedWasHiddenForPrint=false;addEventListener('beforeprint',()=>{const x=$('#advanced');_advancedWasHiddenForPrint=!!x?.hidden;if(x)x.hidden=false;});addEventListener('afterprint',()=>{const x=$('#advanced');if(x&&_advancedWasHiddenForPrint)x.hidden=true;_advancedWasHiddenForPrint=false;});
  $('#pdfBtn').onclick=()=>window.print();$('#odsBtn').onclick=()=>E.exportOds(report,exportAudit,{reports:analysisReports,history:historyAnalytics,matchAnalytics:a});$('#xlsxBtn').onclick=()=>E.exportXlsx(report,exportAudit,{reports:analysisReports,history:historyAnalytics,matchAnalytics:a});$('#backBtn').onclick=()=>location.href='../Historial/index.html';
}catch(e){console.error(e);$('#error').hidden=false;$('#error').textContent=e.message||String(e);$('#backBtn').onclick=()=>location.href='../Historial/index.html';}
})();
