'use strict';

const PHASE = Object.freeze({
  SERVEI: 'SERVEI',
  RECEPCIO: 'RECEPCIO',
  DEFENSA: 'DEFENSA',
  COLLOCACIO: 'COLLOCACIO',
  ATAC: 'ATAC',
  BLOQUEIG: 'BLOQUEIG'
});

const ACTION = Object.freeze({
  MATCH_START: 'MATCH_START',
  SERVEI: 'SERVEI',
  RECEPCIO: 'RECEPCIO',
  DEFENSA: 'DEFENSA',
  COLLOCACIO: 'COLLOCACIO',
  ATAC: 'ATAC',
  BLOQUEIG: 'BLOQUEIG',
  SALVADA: 'SALVADA',
  POINT: 'POINT',
  SOS_AVAILABLE: 'SOS_AVAILABLE',
  SOS_ACTIVATE: 'SOS_ACTIVATE',
  CAMP_RIVAL: 'CAMP_RIVAL',
  ROTATION: 'ROTATION',
  POSITION_CHANGE: 'POSITION_CHANGE',
  SUBSTITUTION: 'SUBSTITUTION',
  SCORE_CORRECTION: 'SCORE_CORRECTION',
  SET_END: 'SET_END',
  SET_START: 'SET_START',
  MATCH_END: 'MATCH_END'
});

const STAT_ACTIONS_ANNA = new Set([
  ACTION.SERVEI,
  ACTION.RECEPCIO,
  ACTION.DEFENSA,
  ACTION.COLLOCACIO,
  ACTION.ATAC
]);

module.exports = { PHASE, ACTION, STAT_ACTIONS_ANNA };
