(async()=>{
'use strict';await Pro2TeamStore.ready;const $=s=>document.querySelector(s);const teamId=new URLSearchParams(location.search).get('team');const team=Pro2TeamStore.getTeam(teamId);if(!team){location.href='index.html';return}
let editingPlayerId=null;const modal=$('#playerModal'),list=$('#rosterList');
const active=()=>((Pro2TeamStore.getTeam(teamId)?.players)||[]).filter(p=>p.active!==false).sort((a,b)=>a.number-b.number||a.name.localeCompare(b.name,'ca'));
function openModal(){modal.classList.add('open');modal.setAttribute('aria-hidden','false')}function closeModal(){modal.classList.remove('open');modal.setAttribute('aria-hidden','true')}
function render(){const current=Pro2TeamStore.getTeam(teamId);const players=active();$('#rosterTitle').textContent='Plantilla · '+current.name;$('#rosterCount').textContent=`${players.length} jugador${players.length===1?'':'s'}/es`;list.innerHTML='';if(!players.length){list.innerHTML='<div class="empty-state">Encara no hi ha jugadors/es en aquesta plantilla.</div>';return}players.forEach(p=>{const row=document.createElement('div');row.className='player-row';row.innerHTML=`<div class="player-id"><div class="player-number">${p.number}</div><div class="player-name">${p.name}</div></div><div class="player-tools"><button class="edit-player" type="button">Editar</button><button class="remove-player" type="button">Treure</button></div>`;row.querySelector('.edit-player').onclick=()=>edit(p.playerId);row.querySelector('.remove-player').onclick=()=>remove(p.playerId);list.append(row)})}
function edit(pid=null){editingPlayerId=pid;const current=Pro2TeamStore.getTeam(teamId),p=pid?(current.players||[]).find(x=>x.playerId===pid):null;$('#playerModalTitle').textContent=p?'Editar jugador/a':'Afegir jugador/a';$('#playerNumberInput').value=p?.number??'';$('#playerNameInput').value=p?.name||'';openModal();setTimeout(()=>$('#playerNumberInput').focus(),0)}
async function save(){const number=Number($('#playerNumberInput').value),name=$('#playerNameInput').value.trim();if(!Number.isInteger(number)||number<0||number>99){alert('Introdueix un dorsal vàlid entre 0 i 99.');return}if(!name){alert('Escriu el nom.');return}try{if(editingPlayerId)await Pro2TeamStore.updatePlayer(teamId,editingPlayerId,{number,name});else await Pro2TeamStore.addPlayer(teamId,{number,name});closeModal();render()}catch(e){alert(e.message||String(e))}}
async function remove(pid){const current=Pro2TeamStore.getTeam(teamId),p=(current.players||[]).find(x=>x.playerId===pid);if(!p||!confirm(`Treure ${p.name} de la plantilla?`))return;try{await Pro2TeamStore.setPlayerActive(teamId,pid,false);render()}catch(e){alert(e.message||String(e))}}
$('#addPlayer').onclick=()=>edit();$('#cancelPlayer').onclick=closeModal;$('#savePlayer').onclick=save;modal.onclick=e=>{if(e.target===modal)closeModal()};document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});
function positionWallCrest(){const crest=document.getElementById('wallCrest'),bg=document.querySelector('.bg');if(!crest||!bg)return;const naturalW=1672,naturalH=941,rect=bg.getBoundingClientRect(),w=rect.width,h=rect.height,scale=Math.max(w/naturalW,h/naturalH),renderedW=naturalW*scale,renderedH=naturalH*scale,sourceX=naturalW*.5064,sourceY=naturalH*.282;let offsetX=(w-renderedW)/2,offsetY=(h-renderedH)/2;if(matchMedia('(orientation:portrait)').matches)offsetX=(w-renderedW)*.40;const centerX=offsetX+sourceX*scale,centerY=offsetY+sourceY*scale,desired=Math.max(82,Math.min(150,136*scale));crest.style.width=desired+'px';const r=crest.getBoundingClientRect();crest.style.left=(centerX-(r.width||desired)/2)+'px';crest.style.top=(centerY-(r.height||desired*1.28)/2)+'px';}
addEventListener('resize',positionWallCrest,{passive:true});positionWallCrest();render();
})();
