'use strict';
const fs=require('fs'),path=require('path'),assert=require('assert');
const {createMatchFromDraft}=require('../src/match-factory');
const {MatchEngine}=require('../src/match-engine');
const {MemoryStorageAdapter}=require('../src/storage-memory');
const {Pro2Storage}=require('../src/storage-service');
const {validateActionLog,verifyReplayConsistency,makeIntegrity,verifyIntegrity,assessIntegrity,recoverStateFromActionLog}=require('../src/session-integrity');
const draft=JSON.parse(fs.readFileSync(path.join(__dirname,'../fixtures/draft.json'),'utf8'));
function fresh(id='integrity'){const {state,actionLog}=createMatchFromDraft(draft,{matchId:id,now:'2026-10-05T12:00:00Z'});return new MatchEngine(state,actionLog)}
async function test(name,fn){try{await fn();console.log('PASS',name)}catch(e){console.error('FAIL',name,'\n ',e.stack||e);process.exitCode=1}}
(async()=>{
 await test('ActionLog vàlid passa validació',()=>{const e=fresh();e.ratePlayer('6',2);e.ratePlayer('3',2);assert.equal(validateActionLog(e.log,e.state),true)});
 await test('replay detecta divergència encara que l’ActionLog sigui estructuralment vàlid',()=>{const e=fresh('replay-diverge');e.ratePlayer('6',2);const s=JSON.parse(JSON.stringify(e.state));s.game.phase='ATAC';assert.throws(()=>verifyReplayConsistency(s,e.log),/Integritat.*reproducció/)});
 await test('integritat detecta MatchState manipulat',()=>{const e=fresh('tamper-state');e.ratePlayer('6',2);const i=makeIntegrity(e.state,e.log);const s=JSON.parse(JSON.stringify(e.state));s.game.score.team=99;assert.throws(()=>verifyIntegrity(i,s,e.log),/Integritat/);const a=assessIntegrity(i,s,e.log);assert.equal(a.stateTrusted,false);assert.equal(a.actionLogTrusted,true)});
 await test('integritat detecta ActionLog manipulat',()=>{const e=fresh('tamper-log');e.ratePlayer('6',2);const i=makeIntegrity(e.state,e.log);const l=JSON.parse(JSON.stringify(e.log));l.actions[1].data.value=3;assert.throws(()=>verifyIntegrity(i,e.state,l),/Integritat/)});
 await test('validador detecta seqüència trencada',()=>{const e=fresh('broken-seq');e.ratePlayer('6',2);const l=JSON.parse(JSON.stringify(e.log));l.actions[1].sequence=7;assert.throws(()=>validateActionLog(l,e.state),/Seqüència/)});
 await test('Salvada 0 és rebutjada també al registre carregat',()=>{const e=fresh('save-zero');e.ratePlayer('6',0);e.activateSOS();e.ratePlayer('5',2);const l=JSON.parse(JSON.stringify(e.log));const a=l.actions.find(x=>x.type==='SALVADA');a.data.value=0;assert.throws(()=>validateActionLog(l,e.state),/Salvada/)});
 await test('save/load actiu recupera MatchState si ActionLog és íntegre',async()=>{const a=new MemoryStorageAdapter(),st=new Pro2Storage(a),e=fresh('store-int');e.ratePlayer('6',2);await st.saveActive(e);const raw=await a.get('activeMatches','store-int');assert.equal(raw.integrity?.version,2);assert(raw.integrity?.stateDigest&&raw.integrity?.actionLogDigest);raw.session.state.game.score.team=8;await a.put('activeMatches','store-int',raw);const loaded=await st.loadActive('store-int');assert.equal(loaded.state.game.score.team,e.state.game.score.team);const healed=await a.get('activeMatches','store-int');assert.equal(healed.recoverySource,'actionLog');verifyIntegrity(healed.integrity,healed.session.state,healed.session.actionLog)});
 await test('recuperació activa també repara identity del MatchState',async()=>{const a=new MemoryStorageAdapter(),st=new Pro2Storage(a),e=fresh('identity-heal');e.ratePlayer('6',2);await st.saveActive(e);const raw=await a.get('activeMatches','identity-heal');raw.session.state.identity.matchId='CORRUPTE';await a.put('activeMatches','identity-heal',raw);const loaded=await st.loadActive('identity-heal');assert.equal(loaded.state.identity.matchId,'identity-heal')});
 await test('recuperació activa pot reconstruir un MatchState absent',async()=>{const a=new MemoryStorageAdapter(),st=new Pro2Storage(a),e=fresh('missing-state');e.ratePlayer('6',2);await st.saveActive(e);const raw=await a.get('activeMatches','missing-state');raw.session.state=null;await a.put('activeMatches','missing-state',raw);const loaded=await st.loadActive('missing-state');assert.equal(loaded.state.identity.matchId,'missing-state');assert.equal(loaded.state.game.phase,e.state.game.phase)});
 await test('registre antic sense empremta continua sent llegible',async()=>{const a=new MemoryStorageAdapter(),st=new Pro2Storage(a),e=fresh('legacy-int');const session=e.exportSession();await a.put('activeMatches','legacy-int',{schemaVersion:1,matchId:'legacy-int',session,savedAt:'2026-10-05T12:00:00Z'});const r=await st.loadActive('legacy-int');assert.equal(r.state.identity.matchId,'legacy-int')});
 await test('Historial amb ActionLog manipulat és rebutjat',async()=>{const a=new MemoryStorageAdapter(),st=new Pro2Storage(a),e=fresh('hist-int');e.finishMatch();await st.finalize(e);const raw=await a.get('completedMatches','hist-int');raw.actionLog.actions[0].data.tampered=true;await a.put('completedMatches','hist-int',raw);await assert.rejects(()=>st.getHistory('hist-int'),/Integritat/)});
 await test('Historial recupera finalState i regenera report si ActionLog és íntegre',async()=>{const a=new MemoryStorageAdapter(),st=new Pro2Storage(a),e=fresh('hist-heal');e.finishMatch();await st.finalize(e);const raw=await a.get('completedMatches','hist-heal');raw.finalState.game.score.team=77;raw.report={broken:true};await a.put('completedMatches','hist-heal',raw);const rec=await st.getHistory('hist-heal');assert.notEqual(rec.finalState.game.score.team,77);assert.equal(rec.recoverySource,'actionLog');assert(rec.report&&!rec.report.broken);verifyIntegrity(rec.integrity,rec.finalState,rec.actionLog)});
 await test('recuperació no confia en ActionLog amb digest incorrecte',()=>{const e=fresh('no-heal-log');e.ratePlayer('6',2);const i=makeIntegrity(e.state,e.log);const l=JSON.parse(JSON.stringify(e.log));l.actions[1].data.value=3;const r=recoverStateFromActionLog(i,e.state,l);assert.equal(r.recovered,false);assert.equal(r.reason,'action-log-untrusted')});
 if(!process.exitCode) console.log('\nRESULTAT FINAL: PASS — INTEGRITAT PRO.2 018');
})();
