'use strict';
const assert=require('assert').strict;
const {MemoryStorageAdapter}=require('../src/storage-memory');
const {Pro2BackupService}=require('../src/backup-service');
const {makeMaintenanceJournal,transitionMaintenanceJournal,maintenanceStatus,canCompactMaintenanceJournal,DEFAULT_MAINTENANCE_RETENTION_MS}=require('../src/maintenance-journal');
let pass=0; async function t(n,f){await f();pass++;console.log('PASS',n);} async function stores(a){const o={};for(const n of ['teams','activeMatches','completedMatches','settings'])o[n]=await a.listEntries(n);return o;}
(async()=>{
 await t('035 estat none sense journal',async()=>{const s=new Pro2BackupService(new MemoryStorageAdapter()); const x=await s.getMaintenanceStatus({now:'2026-10-20T00:00:00Z'}); assert.equal(x.status,'none');assert.equal(x.recoveryRequired,false);});
 await t('035 prepared es recovery-pending i mai compactable',async()=>{const a=new MemoryStorageAdapter(), st=await stores(a),j=makeMaintenanceJournal({sourceStores:st,targetStores:st,now:'2026-10-01T00:00:00Z'});await a.writeMaintenanceJournal(j);const s=new Pro2BackupService(a),x=await s.getMaintenanceStatus({now:'2026-10-20T00:00:00Z'});assert.equal(x.status,'recovery-pending');assert.equal(x.compactable,false);const c=await s.compactMaintenanceJournal({now:'2026-10-20T00:00:00Z',minAgeMs:0});assert.equal(c.compacted,false);assert(await a.readMaintenanceJournal());});
 await t('035 committed tampoc es compacta',async()=>{const a=new MemoryStorageAdapter(),st=await stores(a),j=transitionMaintenanceJournal(makeMaintenanceJournal({sourceStores:st,targetStores:st,now:'2026-10-01T00:00:00Z'}),'committed','2026-10-01T00:00:01Z');await a.writeMaintenanceJournal(j);const c=await new Pro2BackupService(a).compactMaintenanceJournal({now:'2026-10-20T00:00:00Z',minAgeMs:0});assert.equal(c.compacted,false);assert.equal(c.reason,'recovery-pending');});
 await t('035 cleared recent es resolt però es conserva',async()=>{const a=new MemoryStorageAdapter(),st=await stores(a);let j=makeMaintenanceJournal({sourceStores:st,targetStores:st,now:'2026-10-10T00:00:00Z'});j=transitionMaintenanceJournal(j,'committed','2026-10-10T00:00:01Z');j=transitionMaintenanceJournal(j,'cleared','2026-10-10T00:00:02Z');await a.writeMaintenanceJournal(j);const s=new Pro2BackupService(a),x=await s.getMaintenanceStatus({now:'2026-10-10T01:00:00Z'});assert.equal(x.status,'resolved');const c=await s.compactMaintenanceJournal({now:'2026-10-10T01:00:00Z'});assert.equal(c.compacted,false);assert.equal(c.reason,'recent');});
 await t('035 cleared antic es compacta de manera segura',async()=>{const a=new MemoryStorageAdapter(),st=await stores(a);let j=makeMaintenanceJournal({sourceStores:st,targetStores:st,now:'2026-10-01T00:00:00Z'});j=transitionMaintenanceJournal(j,'committed','2026-10-01T00:00:01Z');j=transitionMaintenanceJournal(j,'cleared','2026-10-01T00:00:02Z');await a.writeMaintenanceJournal(j);const s=new Pro2BackupService(a),c=await s.compactMaintenanceJournal({now:'2026-10-20T00:00:00Z'});assert.equal(c.compacted,true);assert.equal(await a.readMaintenanceJournal('__maintenanceJournal__:v1',{includeCleared:true}),null);});
 await t('035 llindar de retencio per defecte és 7 dies',async()=>{assert.equal(DEFAULT_MAINTENANCE_RETENTION_MS,7*24*60*60*1000);});
 await t('035 helper rebutja timestamp invàlid sense esborrar',async()=>{const a=new MemoryStorageAdapter(),st=await stores(a);let j=makeMaintenanceJournal({sourceStores:st,targetStores:st,now:'2026-10-01T00:00:00Z'});j=transitionMaintenanceJournal(j,'cleared','2026-10-01T00:00:02Z');j.updatedAt='invalid'; /* reseal impossible: corrupció es detecta abans */ assert.throws(()=>maintenanceStatus(j,'2026-10-20T00:00:00Z'));});
 console.log(`maintenance-diagnostics-035: ${pass} PASS`);
})().catch(e=>{console.error(e);process.exit(1)});
