'use strict';
const fs=require('fs'),path=require('path'),assert=require('assert');
const {createMatchFromDraft}=require('../src/match-factory');
const {MatchEngine}=require('../src/match-engine');
const {buildMatchReport}=require('../src/match-report');
const {ACTION}=require('../src/constants');
const E=require('../../shared/export-pro2.js');
const draft=JSON.parse(fs.readFileSync(path.join(__dirname,'../fixtures/draft.json'),'utf8'));
const {state,actionLog}=createMatchFromDraft(draft,{matchId:'m-export',now:'2026-10-05T12:00:00Z'});
const e=new MatchEngine(state,actionLog);
e._append(ACTION.RECEPCIO,{playerId:'p3',zone:'4',value:0});
e._append(ACTION.SALVADA,{playerId:'p4',zone:'3',value:3});
e._append(ACTION.ATAC,{playerId:'p3',zone:'4',value:2});
e._append(ACTION.BLOQUEIG,{playerId:'p3',zone:'4',value:2});
e.finishSet();e.finishMatch();
const report=buildMatchReport(e.state,e.log);
assert.equal(report.schemaVersion,4);
assert.equal(report.stats.teamAnnaTotal.actions,2);
assert.equal(report.stats.teamSaves.total,1);
assert.equal(report.stats.teamBlocks.total,1);
assert(report.actions.length>=4,'Cal registre normalitzat d’accions');
const save=report.actions.find(a=>a.type===ACTION.SALVADA);
assert(save&&save.playerName&&save.value===3,'La salvada ha de conservar jugadora i valor 3');
assert.equal(E.saveRows(report).length,1);
assert(E.actionRows(report).some(r=>r[2]==='Salvada'));
const x=E.buildXlsxBytes(report),o=E.buildOdsBytes(report);
assert(x.length>2200&&o.length>1400);
assert.equal(String.fromCharCode(x[0],x[1]),'PK');assert.equal(String.fromCharCode(o[0],o[1]),'PK');
for(const name of ['Informe','Estadístiques','Dades partit','Salvades','Per set','Partit']) assert(Buffer.from(x).includes(Buffer.from(name)),`XLSX sense pestanya ${name}`);
for(const name of ['Informe','Estadístiques','Dades partit','Salvades','Per set','Partit']) assert(Buffer.from(o).includes(Buffer.from(name)),`ODS sense pestanya ${name}`);
fs.writeFileSync('/tmp/pro2_export_test.xlsx',x);fs.writeFileSync('/tmp/pro2_export_test.ods',o);
assert(report.stats.bySet[1],'Cal desglossament del set 1');
assert(E.perSetRows(report).length>0,'Calen files per set');
console.log('PASS MatchReport v4 + desglossament per set + XLSX/ODS bytes');
