'use strict';
const assert=require('assert'),fs=require('fs'),path=require('path');
const {makeLegacyImportRecord}=require('../src/legacy-import');
const {reportFromCompletedRecord}=require('../src/match-report');
const {buildMatchAnalytics}=require('../src/anna-analytics');
const X=require('../../shared/export-pro2.js');
const doc=JSON.parse(fs.readFileSync(path.join(__dirname,'../../imports/legacy/Stats_Castellar_Partit_2026-09-20_Gadex.json'),'utf8'));
const rec=makeLegacyImportRecord(doc), report=reportFromCompletedRecord(rec), a=buildMatchAnalytics(report);
const vals=a.ranking.filter(p=>p.efficiency!=null).map(p=>p.efficiency);
for(let i=1;i<vals.length;i++) assert(vals[i-1]>=vals[i],`Rànquing no ordenat per eficiència: ${vals[i-1]} < ${vals[i]}`);
const full=X.fullRows(report).rows, perc=X.percentageRows(report);
assert(!full[5].includes('T'),'La taula principal no ha de tenir la columna T de Salvades');
assert(!perc[3].includes('T'),'La taula de percentatges no ha de tenir la columna T de Salvades');
assert.equal(full[4].filter(x=>x==='SALVADES').length,1);
assert.equal(full[5].slice(-3).join(','),'1,2,3');
const global=X.annaReportRows(report,a);const pos=global.findIndex(r=>r[0]==='VALORACIÓ GLOBAL');assert(pos>=0);
const first=global[pos+2];assert.equal(first[0],a.ranking[0].name);
console.log('PASS 048 — valoració global per eficiència + Salvades sense T + exports coherents');
