'use strict';
const fs=require('fs'),path=require('path'),assert=require('assert');
const {createMatchFromDraft}=require('../src/match-factory');
const {MatchEngine}=require('../src/match-engine');
const {MemoryStorageAdapter}=require('../src/storage-memory');
const {Pro2Storage}=require('../src/storage-service');
const {buildMatchReport}=require('../src/match-report');
const {makeReportIntegrity,assessReportIntegrity,verifyReportIntegrity}=require('../src/report-integrity');
const draft=JSON.parse(fs.readFileSync(path.join(__dirname,'../fixtures/draft.json'),'utf8'));
function fresh(id='report-int-019'){const {state,actionLog}=createMatchFromDraft(draft,{matchId:id,now:'2026-10-05T18:00:00Z'});return new MatchEngine(state,actionLog)}
async function test(name,fn){try{await fn();console.log('PASS',name)}catch(e){console.error('FAIL',name,'\n ',e.stack||e);process.exitCode=1}}
(async()=>{
 await test('finalize desa empremta independent del MatchReport',async()=>{const a=new MemoryStorageAdapter(),st=new Pro2Storage(a),e=fresh('r019-finalize');e.ratePlayer('6',2);e.finishMatch();await st.finalize(e);const raw=await a.get('completedMatches','r019-finalize');assert.equal(raw.reportIntegrity?.version,1);assert(raw.reportIntegrity?.reportDigest);assert(raw.reportIntegrity?.sourceSessionDigest);verifyReportIntegrity(raw.reportIntegrity,raw.report,raw.finalState,raw.actionLog,buildMatchReport(raw.finalState,raw.actionLog))});
 await test('Historial regenera un MatchReport manipulat sense tocar finalState',async()=>{const a=new MemoryStorageAdapter(),st=new Pro2Storage(a),e=fresh('r019-tamper');e.ratePlayer('6',2);e.finishMatch();await st.finalize(e);const raw=await a.get('completedMatches','r019-tamper');const stateBefore=JSON.stringify(raw.finalState);raw.report.stats.teamAnnaActions=999;await a.put('completedMatches','r019-tamper',raw);const rec=await st.getHistory('r019-tamper');assert.notEqual(rec.report.stats.teamAnnaActions,999);assert.equal(JSON.stringify(rec.finalState),stateBefore);assert.equal(rec.reportRecoverySource,'derived-state-actionLog');assert(rec.reportRecoveredAt);verifyReportIntegrity(rec.reportIntegrity,rec.report,rec.finalState,rec.actionLog,buildMatchReport(rec.finalState,rec.actionLog))});
 await test('Historial regenera un MatchReport absent',async()=>{const a=new MemoryStorageAdapter(),st=new Pro2Storage(a),e=fresh('r019-missing');e.finishMatch();await st.finalize(e);const raw=await a.get('completedMatches','r019-missing');raw.report=null;await a.put('completedMatches','r019-missing',raw);const rec=await st.getHistory('r019-missing');assert(rec.report&&rec.report.matchId==='r019-missing');assert(rec.reportIntegrity?.reportDigest)});
 await test('registre 018 sense reportIntegrity s’actualitza de forma compatible',async()=>{const a=new MemoryStorageAdapter(),st=new Pro2Storage(a),e=fresh('r019-legacy');e.finishMatch();await st.finalize(e);const raw=await a.get('completedMatches','r019-legacy');delete raw.reportIntegrity;await a.put('completedMatches','r019-legacy',raw);const rec=await st.getHistory('r019-legacy');assert(rec.reportIntegrity?.reportDigest);assert.equal(rec.reportRecoverySource,'derived-state-actionLog')});
 await test('empremta del report detecta informe correcte vinculat a una altra sessió',()=>{const e=fresh('r019-source-a');e.finishMatch();const report=buildMatchReport(e.state,e.log);const i=makeReportIntegrity(report,e.state,e.log);const other=fresh('r019-source-b');other.finishMatch();const a=assessReportIntegrity(i,report,other.state,other.log,buildMatchReport(other.state,other.log));assert.equal(a.sourceTrusted,false);assert.equal(a.ok,false)});
 await test('comparació derivada detecta report resegellat però inconsistent',()=>{const e=fresh('r019-derived');e.ratePlayer('6',2);e.finishMatch();const expected=buildMatchReport(e.state,e.log);const bad=JSON.parse(JSON.stringify(expected));bad.audit.activeActions+=1;const forged=makeReportIntegrity(bad,e.state,e.log);const a=assessReportIntegrity(forged,bad,e.state,e.log,expected);assert.equal(a.reportTrusted,true);assert.equal(a.sourceTrusted,true);assert.equal(a.derivationMatches,false);assert.equal(a.ok,false)});
 if(!process.exitCode) console.log('\nRESULTAT FINAL: PASS — INTEGRITAT MATCHREPORT PRO.2 019');
})();
