'use strict';
const assert=require('assert');
const {createMatchFromDraft}=require('../src/match-factory');
const {MatchEngine}=require('../src/match-engine');
const {buildMatchReport,reportFromCompletedRecord}=require('../src/match-report');
const draft=require('../fixtures/draft.json');
const {state,actionLog}=createMatchFromDraft(draft,{matchId:'m-regen',now:'2026-10-05T12:00:00Z'});
const e=new MatchEngine(state,actionLog);
e.ratePlayer('4',2);e.finishSet();e.finishMatch();
const current=buildMatchReport(e.state,e.log);
const stale={...current,schemaVersion:1,stats:{...current.stats,teamAnnaActions:999}};
const rec={matchId:'m-regen',finalState:e.state,actionLog:e.log,report:stale};
const rebuilt=reportFromCompletedRecord(rec);
assert.equal(rebuilt.schemaVersion,4);
assert.notEqual(rebuilt.stats.teamAnnaActions,999);
assert.equal(rebuilt.generatedFrom.lastActionId,e.state.lastActionId);
const fallback=reportFromCompletedRecord({report:stale});
assert.equal(fallback.schemaVersion,1);
console.log('PASS Historial regenera MatchReport des de finalState + ActionLog');
